name: "sample react CI pipeline / workflow"

on:
    push:
        branches:
            - main
            - master

jobs: 
    bulid-and-test:     
           run-on: ubuntu-latest

           steps:
            - name: "setup nod JS"
              uses: actions/setup-node@v2
                
                - Name: "check node version"
                     run: node --version

                  - Name:  "clone the repository"
                  uses: actions/checkout@v2

                  - name: "install dependencies"
                    run: npm install
                  
                  - name: "list directories"
                    run: ls
